name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Cambia esto según tu versión de Node.js

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # Si tienes pruebas, asegúrate de definirlas

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Cambia esto a tu región

      - name: Deploy to AWS
        run: |
          # Aquí puedes agregar comandos para desplegar tu aplicación.
          # Por ejemplo, ejecutar Terraform apply
          cd path/to/your/terraform/directory
          terraform init
          terraform apply -auto-approve